# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170607_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Video'),
        ),
    ]
