# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170607_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='song',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Song'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
