# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170607_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
