# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 20:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 6, 10, 20, 28, 53, 167442, tzinfo=utc)),
        ),
    ]
