# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20170611_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 6, 11, 17, 58, 50, 907151, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
